[pytest]

pythonpath = .

addopts = -s -v

#addopts = --reruns 2 --reruns-delay 2

BASE_URL = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
USERNAME = Admin
PASSWORD = admin123

markers =
    # Test Type
    smoke: critical tests
    regression: full suite
    sanity: quick checks

    # Priority
    critical: must pass
    high: important
    medium: normal priority
    low: less critical

    # Features
    login: login module tests
    dashboard: dashboard tests
    admin: admin module tests

    # Test Nature
    ui: UI tests
    api: API tests
    e2e: end-to-end tests