from pathlib import Path
from datetime import datetime

class HtmlReport:
    def __init__(self, output='report.html'):
        self.output = Path(output)
        self.rows = []
        self.start = datetime.now()

    def add_result(self, test, duration, status, message='', screenshot_path=None):
        self.rows.append({
            'test': test,
            'duration': round(duration, 2),
            'status': status.upper(),
            'message': message,
            'screenshot': screenshot_path or ''
        })

    def generate(self):
        total = len(self.rows)
        passed = sum(1 for r in self.rows if r['status'] == 'PASSED')
        failed = sum(
            1 for r in self.rows
            if r['status'] in ('FAILED', 'SETUP ERROR', 'TEARDOWN ERROR')
        )
        skipped = sum(1 for r in self.rows if r['status'] == 'SKIPPED')
        reruns = sum(1 for r in self.rows if r['status'] == 'RERUN')
        decisive = passed + failed
        rate = round((passed / decisive) * 100, 1) if decisive else 0
        created = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        html = f'''<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>QA Test Report</title>
<style>
body {{font-family: Segoe UI, Arial; background:#f5f7fb; margin:0; padding:30px; color:#222;}}
.header {{display:flex; justify-content:space-between; align-items:center; margin-bottom:24px;}}
.title {{font-size:32px; font-weight:700;}}
.sub {{color:#666;}}
.rate {{background:#dbeafe; color:#1e3a8a; padding:10px 16px; border-radius:8px; font-weight:bold;}}
.grid {{display:grid; grid-template-columns:repeat(6,1fr); gap:16px; margin-bottom:24px;}}
.card {{background:white; border-radius:18px; padding:18px; box-shadow:0 8px 20px rgba(0,0,0,.08);}}
.metric {{font-size:28px; font-weight:700; margin-top:8px;}}
table {{width:100%; border-collapse:collapse; background:white; border-radius:18px; overflow:hidden; box-shadow:0 8px 20px rgba(0,0,0,.08);}}
th,td {{padding:14px; text-align:left; border-bottom:1px solid #eee; vertical-align:top;}}
th {{background:#111827; color:white;}}
.badge {{padding:6px 10px; border-radius:999px; font-weight:700; font-size:12px; display:inline-block;}}
.pass {{background:#dcfce7; color:#166534;}}
.fail {{background:#fee2e2; color:#991b1b;}}
.skip {{background:#fef9c3; color:#854d0e;}}
.rerun {{background:#ffedd5; color:#9a3412;}}
.setup {{background:#f3e8ff; color:#6b21a8;}}
img {{width:180px; border-radius:10px; cursor:pointer; border:1px solid #ddd;}}
.msg {{max-width:550px; white-space:pre-wrap; word-break:break-word; color:#444;}}
.footer {{margin-top:20px; color:#666;}}
#modal {{display:none; position:fixed; inset:0; background:rgba(0,0,0,.8); align-items:center; justify-content:center;}}
#modal img {{max-width:90%; max-height:90%; width:auto;}}
</style>
<script>
function showImg(src){{document.getElementById('big').src=src;document.getElementById('modal').style.display='flex';}}
function closeImg(){{document.getElementById('modal').style.display='none';}}
</script>
</head>
<body>
<div class='header'>
<div><div class='title'>Test Execution Report</div><div class='sub'>Generated: {created}</div></div>
<div class='sub rate'>Pass Rate: {rate}%</div>
</div>
<div class='grid'>
<div class='card'><div>Total rows</div><div class='metric'>{total}</div></div>
<div class='card'><div>Passed</div><div class='metric'>{passed}</div></div>
<div class='card'><div>Failed</div><div class='metric'>{failed}</div></div>
<div class='card'><div>Skipped</div><div class='metric'>{skipped}</div></div>
<div class='card'><div>Reruns</div><div class='metric'>{reruns}</div></div>
<div class='card'><div>Started</div><div class='metric' style='font-size:18px'>{self.start.strftime('%H:%M:%S')}</div></div>
</div>
<table>
<tr><th>Test</th><th>Duration(s)</th><th>Status</th><th>Message</th><th>Screenshot</th></tr>'''

        def badge_class(st):
            if st == 'PASSED':
                return 'pass'
            if st == 'RERUN':
                return 'rerun'
            if st == 'SKIPPED':
                return 'skip'
            if st in ('SETUP ERROR', 'TEARDOWN ERROR'):
                return 'setup'
            return 'fail'

        for r in self.rows:
            bcls = badge_class(r['status'])
            shot = f"<img src='{r['screenshot']}' onclick=\"showImg('{r['screenshot']}')\">" if r['screenshot'] else '-'
            html += f"<tr><td>{r['test']}</td><td>{r['duration']}</td><td><span class='badge {bcls}'>{r['status']}</span></td><td class='msg'>{r['message']}</td><td>{shot}</td></tr>"

        html += '''</table>
<div class='footer'>Generated by Custom Python QA Reporter</div>
<div id='modal' onclick='closeImg()'><img id='big'></div>
</body></html>'''

        self.output.write_text(html, encoding='utf-8')
        print(f'Report created: {self.output}')
